# 1. 입력 (Input): 카프카에서 가져오기
input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["financial-transactions"]
    codec => "json" # 가져올 때부터 JSON으로 인식해라!
    consumer_threads => 1
  }
}

# 2. 가공 (Filter): 데이터 예쁘게 다듬기
filter {
  # 스프링 부트에서 만든 'timestamp' 문자열을 실제 시간(Date) 데이터 타입으로 변환
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }
}

# 3. 출력 (Output): Elasticsearch 도서관에 저장
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "fds-logs-%{+YYYY.MM.dd}" # 날짜별로 책장(인덱스)을 나눠서 저장
    user => "elastic"
    password => "Sentinel123!"
  }

  # 우리가 눈으로 확인할 수 있게 터미널에도 출력
  stdout {
    codec => rubydebug
  }
}